from enum import Enum

class DocumentStatus(str, Enum):
    NEW="NEW"; CHECKING="CHECKING"; OK="OK"; WARNING="WARNING"; ERROR="ERROR"; SKIPPED="SKIPPED"; READY="READY"; MERGING="MERGING"; MERGED="MERGED"; INTERRUPTED="INTERRUPTED"

class JobState(str, Enum):
    IDLE="IDLE"; SCANNING="SCANNING"; PREFLIGHT="PREFLIGHT"; READY="READY"; RUNNING="RUNNING"; PAUSED="PAUSED"; STOPPING="STOPPING"; DONE="DONE"; DONE_WITH_WARNINGS="DONE_WITH_WARNINGS"; ERROR="ERROR"; INTERRUPTED="INTERRUPTED"

class SortMode(str, Enum):
    NATURAL_NAME="NATURAL_NAME"; FOLDER_ORDER="FOLDER_ORDER"; MODIFIED_DATE_ASC="MODIFIED_DATE_ASC"; MODIFIED_DATE_DESC="MODIFIED_DATE_DESC"; MANUAL="MANUAL"
    # Secība no CSV/JSON saraksta. Tā ir ABSOLŪTA: natural sort pēc tam netiek pielietots.
    ORDER_LIST="ORDER_LIST"


class OrderListStatus(str, Enum):
    """CSV/JSON saraksta ieraksta statuss pēc matching pret projekta failiem."""
    FOUND="FOUND"; MISSING="MISSING"; AMBIGUOUS="AMBIGUOUS"; DUPLICATE="DUPLICATE"; IGNORED="IGNORED"


# Statusi, kas STRICT MODE bloķē merge (IGNORED nebloķē — tas ir apzināts izlaidums).
BLOCKING_ORDER_STATUSES=frozenset({OrderListStatus.MISSING,OrderListStatus.AMBIGUOUS,OrderListStatus.DUPLICATE})

class SeparatorMode(str, Enum):
    NONE="NONE"; PAGE_BREAK="PAGE_BREAK"; SECTION_BREAK_NEXT_PAGE="SECTION_BREAK_NEXT_PAGE"; SECTION_BREAK_CONTINUOUS="SECTION_BREAK_CONTINUOUS"

class ErrorPolicy(str, Enum):
    STOP_ON_ERROR="STOP_ON_ERROR"; SKIP_AND_CONTINUE="SKIP_AND_CONTINUE"; RETRY_ONCE_THEN_SKIP="RETRY_ONCE_THEN_SKIP"
